# Generated by Django 5.0.6 on 2024-08-12 16:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("position", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pre_open", "Pre_Open"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="pre_open",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("max_length", models.IntegerField()),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="recruitment.jobposting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EssayAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=255)),
                ("applicant_email", models.EmailField(max_length=255)),
                ("applicant_phone_number", models.CharField(max_length=15)),
                ("answer_text", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="recruitment.essayquestion",
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="recruitment.jobposting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=255)),
                ("applicant_email", models.EmailField(max_length=255)),
                ("summarys", models.JSONField(default=list)),
                (
                    "techs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "jobs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("questions", models.JSONField(default=list)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="recruitment.jobposting",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="summary",
            constraint=models.UniqueConstraint(
                fields=("job_posting", "applicant_name", "applicant_email"),
                name="unique_summary_per_applicant_per_job",
            ),
        ),
    ]
