# Generated by Django 5.0.6 on 2024-07-18 09:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=255)),
                ("applicant_email", models.EmailField(max_length=255)),
                ("summarys", models.JSONField(default=list)),
                (
                    "techs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "jobs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("questions", models.JSONField(default=list)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="recruitment.jobposting",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="summary",
            constraint=models.UniqueConstraint(
                fields=("job_posting", "applicant_name", "applicant_email"),
                name="unique_summary_per_applicant_per_job",
            ),
        ),
    ]
