# Generated by Django 5.0.6 on 2024-07-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_summary_summary_unique_summary_per_applicant_per_job"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="essayanswer",
            name="unique_applicant_application",
        ),
    ]
