# Generated by Django 5.0.6 on 2024-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("to_do_assigned", "To Do Assigned"),
                            ("event_created", "Event Created"),
                            ("appointment_created", "Appointment Created"),
                            ("agenda_reviewed", "Agenda Reviewed"),
                            ("agenda_requested", "Agenda Requested"),
                            ("pto_requested", "PTO Requested"),
                            ("pto_reviewed", "PTO Reviewed"),
                            ("new_message", "New Message"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("context", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
