# Generated by Django 5.0.6 on 2024-07-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("to_do_assigned", "To Do Assigned"),
                    ("event_created", "Event Created"),
                    ("appointment_created", "Appointment Created"),
                    ("agenda_reviewed", "Agenda Reviewed"),
                    ("agenda_requested", "Agenda Requested"),
                    ("pto_requested", "PTO Requested"),
                    ("pto_reviewed", "PTO Reviewed"),
                    ("new_message", "New Message"),
                ],
                max_length=30,
            ),
        ),
    ]
