services:
  web:
    environment:
      DJANGO_ENV: "development"
      TZ: "Asia/Seoul"
    image: luminari_web:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      #- ./src:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - ./media:/app/media
    expose:
      - 8000

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: luminari_nginx:latest
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./docker/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./media:/app/media
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - web

  certbot:
    image: luminari_certbot:latest
    build:
      context: .
      dockerfile: docker/certbot/Dockerfile
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static_volume:
  media_volume:
