services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres-luminari
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-luminari
    restart: always
    ports:
      - "6379:6379"
