# Generated by Django 5.0.6 on 2024-08-12 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("clock_in", models.DateTimeField(blank=True, null=True)),
                ("clock_out", models.DateTimeField(blank=True, null=True)),
                ("is_late", models.BooleanField(default=False)),
                ("is_early_leave", models.BooleanField(default=False)),
                ("is_excused", models.BooleanField(default=False)),
                ("overtime", models.FloatField(default=0.0)),
                ("clock_in_note", models.TextField(blank=True, null=True)),
                ("clock_out_note", models.TextField(blank=True, null=True)),
                ("hr_note", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["date"],
                "get_latest_by": "date",
            },
        ),
    ]
