# Generated by Django 5.0.6 on 2024-08-12 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval", "0002_initial"),
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="drafter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approval",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="agenda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="approval.agenda",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="references",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewstep",
            name="agenda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_steps",
                to="approval.agenda",
            ),
        ),
        migrations.AddField(
            model_name="reviewstep",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewed_agendas",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="reviewstep",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewstep",
            unique_together={("agenda", "step_order")},
        ),
    ]
