# Generated by Django 5.0.6 on 2024-07-15 16:14

import approval.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0003_agenda_reference_reviewstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="agenda_type",
            field=models.CharField(
                choices=[("receipt", "Receipt"), ("general", "General")],
                default="general",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=approval.models.agenda_document_directory_path,
            ),
        ),
    ]
