# Generated by Django 5.0.6 on 2024-07-15 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0004_agenda_agenda_type_agenda_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
