# Generated by Django 5.0.6 on 2024-07-13 08:21

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_employee_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.user_directory_path
            ),
        ),
    ]
