# Generated by Django 5.0.6 on 2024-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_employee_certifications_employee_hobbies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="duration",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="role",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
