# Generated by Django 5.0.6 on 2024-07-16 16:25

import chatbot.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_alter_message_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=chatbot.models.chatbot_document_directory_path
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("onboarding_offboarding", "Onboarding / Offboarding"),
                            ("company_policies", "Company Policies"),
                            ("others", "Others"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="message",
            old_name="datetime",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
