# Generated by Django 5.0.6 on 2024-07-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_chatbotdocument_rename_datetime_message_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotdocument",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="chatbotdocument",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
