# Generated by Django 5.0.6 on 2024-07-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_chatbotmessage_delete_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatbotmessage",
            old_name="message",
            new_name="author",
        ),
    ]
