# Generated by Django 5.0.6 on 2024-07-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0009_documents"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Documents",
        ),
    ]
