# Generated by Django 5.0.6 on 2024-08-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            """
            -- Create the extension if it doesn't exist
            CREATE EXTENSION IF NOT EXISTS vector;

            -- Create the documents table
            CREATE TABLE IF NOT EXISTS documents (
                id UUID PRIMARY KEY,
                content TEXT,
                metadata JSONB,
                embedding VECTOR(1536)
            );

            -- Create the match_documents function
            CREATE FUNCTION match_documents (
                query_embedding VECTOR(1536),
                filter JSONB DEFAULT '{}'
            ) RETURNS TABLE (
                id UUID,
                content TEXT,
                metadata JSONB,
                similarity FLOAT
            ) LANGUAGE plpgsql AS $$
            #variable_conflict use_column
            BEGIN
                RETURN QUERY
                SELECT
                    id,
                    content,
                    metadata,
                    1 - (documents.embedding <=> query_embedding) AS similarity
                FROM documents
                WHERE metadata @> filter
                ORDER BY documents.embedding <=> query_embedding;
            END;
            $$;

            -- Create the mentorship_documents table
            CREATE TABLE IF NOT EXISTS mentorship_documents (
                id UUID PRIMARY KEY,
                content TEXT,
                metadata JSONB,
                embedding VECTOR(3072)
            );

            -- Create the mentorship_match_documents function
            CREATE FUNCTION mentorship_match_documents (
                query_embedding VECTOR(3072),
                filter JSONB DEFAULT '{}'
            ) RETURNS TABLE (
                id UUID,
                content TEXT,
                metadata JSONB,
                similarity FLOAT
            ) LANGUAGE plpgsql AS $$
            #variable_conflict use_column
            BEGIN
                RETURN QUERY
                SELECT
                    id,
                    content,
                    metadata,
                    1 - (mentorship_documents.embedding <=> query_embedding) AS similarity
                FROM mentorship_documents
                WHERE metadata @> filter
                ORDER BY mentorship_documents.embedding <=> query_embedding;
            END;
            $$;
            """,
            reverse_sql="""
            -- Drop the function and table if rolling back
            DROP FUNCTION IF EXISTS mentorship_match_documents;
            DROP TABLE IF EXISTS mentorship_documents;
            DROP FUNCTION IF EXISTS match_documents;
            DROP TABLE IF EXISTS documents;
            DROP EXTENSION IF EXISTS vector;
            """,
        ),
    ]
