# Generated by Django 5.0.6 on 2024-07-20 09:52

import ptos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pto",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=ptos.models.pto_document_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="pto",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="pto",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
